### ISSUE TITLE
未定义名称 todo 请问如何处理？

### ISSUE THREAD

**Issue by GM01A** [foyoux/docts#5]
![QQ截图20231128144004](https://github.com/foyoux/docts/assets/44726545/1c275ef7-b936-464e-8352-e3692c229bb3)

报错信息：
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
NameError: name 'todo' is not defined

**Comment by lemisky** [comment]
铁子，用这里的示例代码，

https://github.com/foyoux/docts/tree/main?tab=readme-ov-file#%E7%BF%BB%E8%AF%91-xlf-%E6%96%87%E4%BB%B6

这个不能称为一个库，只能叫一个脚本，里面代码很少，有问题自己看哈，反正是可以用
